### ISSUE TITLE
Error on getting volume

### ISSUE THREAD

**Issue by mikemey01** [mikemey01/Markets#41]
04-21 11:03:20.328 6317-6317/com.chariotinstruments.markets E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.chariotinstruments.markets, PID: 6317
                                                                              java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
                                                                                  at java.util.ArrayList.get(ArrayList.java:310)
                                                                                  at com.chariotinstruments.markets.MarketDay.getLatestCandleVolume(MarketDay.java:44)
                                                                                  at com.chariotinstruments.markets.PhaseOneIndicatorControl.calcLastCandleVolume(PhaseOneIndicatorControl.java:85)
                                                                                  at com.chariotinstruments.markets.PhaseOneIndicatorControl.calculateIndicators(PhaseOneIndicatorControl.java:67)
                                                                                  at com.chariotinstruments.markets.PhaseOneControl.onParseDataComplete(PhaseOneControl.java:213)
                                                                                  at com.chariotinstruments.markets.ParseData.onPostExecute(ParseData.java:84)
                                                                                  at com.chariotinstruments.markets.ParseData.onPostExecute(ParseData.java:23)
                                                                                  at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                                  at android.os.AsyncTask.access$500(AsyncTask.java:180)
                                                                                  at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:158)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by mikemey01** [comment]
Error is at:
    public long getLatestCandleVolume(){
        return _marketCandles.get(_marketCandles.size()-2).getVolume();
    }
in MarketDay.java

Index out of bounds. Need to check the size of the arraylist before returning data from it.

**Comment by mikemey01** [comment]
fixed.
