### ISSUE TITLE
Problem from 5/19 - something with parsing JSON from optionOrderPreview.

### ISSUE THREAD

**Issue by mikemey01** [mikemey01/Markets#49]
05-19 11:31:26.781 17025-17600/com.chariotinstruments.markets W/System.err: org.json.JSONException: Value [] at quotes of type org.json.JSONArray cannot be converted to JSONObject
05-19 11:31:26.791 17025-17600/com.chariotinstruments.markets W/System.err:     at org.json.JSON.typeMismatch(JSON.java:100)
05-19 11:31:26.791 17025-17600/com.chariotinstruments.markets W/System.err:     at org.json.JSONObject.getJSONObject(JSONObject.java:613)
05-19 11:31:26.791 17025-17600/com.chariotinstruments.markets W/System.err:     at com.chariotinstruments.markets.ParseOptionOrderPreview.parseJSON(ParseOptionOrderPreview.java:88)
05-19 11:31:26.791 17025-17600/com.chariotinstruments.markets W/System.err:     at com.chariotinstruments.markets.ParseOptionOrderPreview.doInBackground(ParseOptionOrderPreview.java:64)
05-19 11:31:26.791 17025-17600/com.chariotinstruments.markets W/System.err:     at com.chariotinstruments.markets.ParseOptionOrderPreview.doInBackground(ParseOptionOrderPreview.java:20)
05-19 11:31:26.791 17025-17600/com.chariotinstruments.markets W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
05-19 11:31:26.791 17025-17600/com.chariotinstruments.markets W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-19 11:31:26.791 17025-17600/com.chariotinstruments.markets W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
05-19 11:31:26.791 17025-17600/com.chariotinstruments.markets W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-19 11:31:26.791 17025-17600/com.chariotinstruments.markets W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-19 11:31:26.791 17025-17600/com.chariotinstruments.markets W/System.err:     at java.lang.Thread.run(Thread.java:818)
05-19 11:31:26.791 17025-17025/com.chariotinstruments.markets D/AndroidRuntime: Shutting down VM
05-19 11:31:26.791 17025-17025/com.chariotinstruments.markets E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.chariotinstruments.markets, PID: 17025
                                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'void com.chariotinstruments.markets.FixmlModel.setLimitPrice(double)' on a null object reference
                                                                                    at com.chariotinstruments.markets.PhaseOneTradeControl.onParseOptionOrderPreviewComplete(PhaseOneTradeControl.java:77)
                                                                                    at com.chariotinstruments.markets.ParseOptionOrderPreview.onPostExecute(ParseOptionOrderPreview.java:75)
                                                                                    at com.chariotinstruments.markets.ParseOptionOrderPreview.onPostExecute(ParseOptionOrderPreview.java:20)
                                                                                    at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                                    at android.os.AsyncTask.access$500(AsyncTask.java:180)
                                                                                    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:158)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by mikemey01** [comment]
The issue here is that the quantity was set to 100 which doesn't work even with order previews. Need to catch that error and throw it to the console instead of cratering the app.
